// ============================================================
// ScanScreen — one-time diagnostic scan results
// ============================================================

import React, { useEffect, useCallback, useState } from 'react';
import { useThemeColors } from '../utils/hooks';
import { useScanStore } from '../store/scanStore';
import { DTCCard } from '../components/DTCCard';
import { StatusBadge } from '../components/StatusBadge';
import { DTC, FreezeFrame, RawLogEntry } from '../types';
import html2canvas from 'html2canvas-pro';
import { jsPDF } from 'jspdf';

interface Props {
  onNavigate: (screen: string, params?: any) => void;
}

export function ScanScreen({ onNavigate }: Props) {
  const theme = useThemeColors();
  const {
    isScanning,
    scanProgress,
    scanStage,
    currentResult,
    error,
    startScan,
    clearCodes,
  } = useScanStore();
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [showClearConfirm, setShowClearConfirm] = useState(false);
  const [clearConfirmText, setClearConfirmText] = useState('');

  useEffect(() => {
    if (!currentResult && !isScanning) {
      startScan();
    }
  }, []);

  const handleClearCodes = useCallback(async () => {
    setShowClearConfirm(false);
    setClearConfirmText('');
    const success = await clearCodes();
    if (success) {
      window.alert('Codes cleared. Re-scanning to verify...');
      startScan();
    } else {
      window.alert('Failed to clear codes. Please try again.');
    }
  }, [clearCodes, startScan]);

  const buildMarkdown = useCallback(() => {
    if (!currentResult) return '';
    const r = currentResult;
    const lines = [
      '# OBD2 Scan Report',
      '',
      `**Date:** ${new Date(r.timestamp).toLocaleString()}`,
      '',
      '## Vehicle Info',
      '',
      `| Field | Value |`,
      `|---|---|`,
      `| VIN | ${r.vin ?? 'N/A'} |`,
      `| Check Engine | ${r.milStatus ? '**ON**' : 'OFF'} |`,
      `| OBD Standard | ${r.obdStandard ?? 'N/A'} |`,
      `| Calibration ID | ${r.calibrationId ?? 'N/A'} |`,
    ];

    const allDTCs = [...r.storedDTCs, ...r.pendingDTCs, ...r.permanentDTCs];
    lines.push('', `## Fault Codes (${allDTCs.length})`, '');

    if (allDTCs.length === 0) {
      lines.push('No fault codes found.');
    } else {
      lines.push('| Code | Type | Severity | Description |', '|---|---|---|---|');
      for (const d of allDTCs) {
        lines.push(`| ${d.code} | ${d.type} | ${d.severity} | ${d.description} |`);
      }
    }

    if (r.freezeFrame) {
      const ff = r.freezeFrame;
      lines.push('', '## Freeze Frame Data', '', '| Parameter | Value |', '|---|---|');
      const params = [
        ['Engine RPM', ff.rpm, 'RPM'], ['Vehicle Speed', ff.speed, 'km/h'],
        ['Coolant Temp', ff.coolantTemp, '°C'], ['Engine Load', ff.engineLoad, '%'],
        ['STFT', ff.shortTermFuelTrim, '%'], ['LTFT', ff.longTermFuelTrim, '%'],
        ['MAP', ff.intakeManifoldPressure, 'kPa'], ['Timing', ff.timingAdvance, '°'],
      ];
      for (const [name, val, unit] of params) {
        lines.push(`| ${name} | ${val !== null ? `${val} ${unit}` : 'N/A'} |`);
      }
    }

    lines.push('', '---', `*Generated by OBD2 Scanner*`);
    return lines.join('\n');
  }, [currentResult]);

  const handleExportMarkdown = useCallback(async () => {
    const md = buildMarkdown();
    if (!md) return;
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `obd2-scan-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [buildMarkdown]);

  const handleExportPNG = useCallback(async () => {
    const el = document.getElementById('scan-results');
    if (!el) return;
    try {
      const canvas = await html2canvas(el, { backgroundColor: '#F2F2F7', scale: 2, logging: false });
      const url = canvas.toDataURL('image/png');
      const a = document.createElement('a');
      a.href = url;
      a.download = `obd2-scan-${new Date().toISOString().slice(0, 10)}.png`;
      a.click();
    } catch { window.alert('Could not capture screenshot.'); }
  }, []);

  const handleExportPDF = useCallback(async () => {
    const el = document.getElementById('scan-results');
    if (!el) return;
    try {
      const canvas = await html2canvas(el, { backgroundColor: '#FFFFFF', scale: 2, logging: false });
      const imgData = canvas.toDataURL('image/png');
      const imgW = canvas.width;
      const imgH = canvas.height;
      const pdfW = 210; // A4 width in mm
      const pdfH = (imgH * pdfW) / imgW;
      const pdf = new jsPDF({ orientation: pdfH > 297 ? 'portrait' : 'portrait', unit: 'mm', format: [pdfW, Math.max(pdfH, 297)] });
      pdf.addImage(imgData, 'PNG', 0, 0, pdfW, pdfH);
      pdf.save(`obd2-scan-${new Date().toISOString().slice(0, 10)}.pdf`);
    } catch { window.alert('Could not generate PDF.'); }
  }, []);

  const formatDate = (ts: number) =>
    new Date(ts).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });

  // --- Scanning in progress ---
  if (isScanning) {
    return (
      <div
        style={{
          minHeight: '100%',
          backgroundColor: theme.background,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          padding: 32,
        }}
      >
        <div
          style={{
            width: 40,
            height: 40,
            border: `4px solid ${theme.gaugeArc}`,
            borderTopColor: theme.primary,
            borderRadius: '50%',
            animation: 'spin 1s linear infinite',
          }}
        />
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
        <div style={{ fontSize: 18, fontWeight: 500, color: theme.text, marginTop: 20 }}>
          {scanStage}
        </div>
        <div
          style={{
            width: '80%',
            maxWidth: 320,
            height: 6,
            borderRadius: 3,
            backgroundColor: theme.gaugeArc,
            marginTop: 16,
            overflow: 'hidden',
          }}
        >
          <div
            style={{
              width: `${scanProgress * 100}%`,
              height: '100%',
              borderRadius: 3,
              backgroundColor: theme.primary,
              transition: 'width 0.3s ease',
            }}
          />
        </div>
        <div style={{ fontSize: 13, color: theme.textSecondary, marginTop: 8 }}>
          {Math.round(scanProgress * 100)}%
        </div>
      </div>
    );
  }

  // --- No result ---
  if (!currentResult) {
    return (
      <div
        style={{
          minHeight: '100%',
          backgroundColor: theme.background,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          padding: 32,
        }}
      >
        <div style={{ fontSize: 18, color: theme.text, textAlign: 'center', marginBottom: 20 }}>
          {error ?? 'No scan results'}
        </div>
        <button
          onClick={startScan}
          style={{
            padding: '12px 32px',
            fontSize: 16,
            fontWeight: 600,
            color: '#FFFFFF',
            backgroundColor: theme.primary,
            border: 'none',
            borderRadius: 10,
            cursor: 'pointer',
          }}
        >
          Retry Scan
        </button>
      </div>
    );
  }

  // --- Results ---
  const r = currentResult;
  const totalDTCs = r.storedDTCs.length + r.pendingDTCs.length + r.permanentDTCs.length;

  const renderDTCSection = (title: string, dtcs: DTC[]) => {
    if (dtcs.length === 0) return null;
    return (
      <div style={{ marginBottom: 16 }}>
        <div
          style={{
            fontSize: 11,
            fontWeight: 600,
            letterSpacing: 0.5,
            color: theme.textSecondary,
            marginBottom: 8,
            textTransform: 'uppercase',
          }}
        >
          {title} ({dtcs.length})
        </div>
        {dtcs.map((dtc) => (
          <DTCCard key={dtc.code + dtc.type} dtc={dtc} />
        ))}
      </div>
    );
  };

  return (
    <div style={{ minHeight: '100%', backgroundColor: theme.background, padding: 24, paddingBottom: 48 }}>
      <div id="scan-results">
      {/* Vehicle Info Card */}
      <div
        style={{
          backgroundColor: theme.surface,
          border: `1px solid ${theme.border}`,
          borderRadius: 14,
          padding: 16,
          marginBottom: 16,
        }}
      >
        <div
          style={{
            fontSize: 11,
            fontWeight: 600,
            letterSpacing: 0.5,
            color: theme.textSecondary,
            marginBottom: 10,
            textTransform: 'uppercase',
          }}
        >
          Vehicle Info
        </div>
        {[
          { label: 'VIN', node: <span style={{ fontSize: 14, fontWeight: 500, color: theme.text, fontFamily: 'monospace', userSelect: 'all' as const }}>{r.vin ?? 'N/A'}</span> },
          {
            label: 'Check Engine',
            node: (
              <StatusBadge
                label={r.milStatus ? 'ON' : 'OFF'}
                color={r.milStatus ? theme.critical : theme.success}
                size="small"
              />
            ),
          },
          { label: 'OBD Standard', node: <span style={{ fontSize: 14, fontWeight: 500, color: theme.text }}>{r.obdStandard ?? 'N/A'}</span> },
          { label: 'Scanned', node: <span style={{ fontSize: 14, fontWeight: 500, color: theme.text }}>{formatDate(r.timestamp)}</span> },
        ].map((row) => (
          <div
            key={row.label}
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: '6px 0',
            }}
          >
            <span style={{ fontSize: 14, color: theme.textSecondary }}>{row.label}</span>
            {row.node}
          </div>
        ))}
      </div>

      {/* DTC Summary */}
      <div
        style={{
          backgroundColor: theme.surface,
          border: `1px solid ${theme.border}`,
          borderRadius: 14,
          padding: 16,
          marginBottom: 16,
        }}
      >
        <div
          style={{
            fontSize: 11,
            fontWeight: 600,
            letterSpacing: 0.5,
            color: theme.textSecondary,
            marginBottom: 10,
            textTransform: 'uppercase',
          }}
        >
          Fault Codes
        </div>
        {totalDTCs === 0 ? (
          <div style={{ textAlign: 'center', padding: '16px 0' }}>
            <div style={{ fontSize: 18, fontWeight: 600, color: theme.success }}>
              No fault codes found
            </div>
            <div style={{ fontSize: 13, color: theme.textSecondary, marginTop: 4 }}>
              Your vehicle is not reporting any issues
            </div>
          </div>
        ) : (
          <div style={{ fontSize: 16, fontWeight: 600, color: theme.text }}>
            {totalDTCs} code{totalDTCs !== 1 ? 's' : ''} found
          </div>
        )}
      </div>

      {/* DTC Sections */}
      {renderDTCSection('Stored', r.storedDTCs)}
      {renderDTCSection('Pending', r.pendingDTCs)}
      {renderDTCSection('Permanent', r.permanentDTCs)}

      {/* Freeze Frame */}
      {r.freezeFrame && <FreezeFrameTable frame={r.freezeFrame} theme={theme} />}

      {/* Raw Data Log (collapsible) */}
      {r.rawLog && r.rawLog.length > 0 && <RawDataLog entries={r.rawLog} theme={theme} />}

      </div>{/* end scan-results */}

      {/* Action Buttons */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginTop: 20 }}>
        {totalDTCs > 0 && (
          <button
            onClick={() => { setShowClearConfirm(true); setClearConfirmText(''); }}
            style={{
              width: '100%',
              padding: '14px 0',
              fontSize: 16,
              fontWeight: 600,
              color: '#FFFFFF',
              backgroundColor: theme.critical,
              border: 'none',
              borderRadius: 10,
              cursor: 'pointer',
            }}
          >
            Clear Codes
          </button>
        )}
        <div style={{ position: 'relative' }}>
          <button
            onClick={() => setShowExportMenu(!showExportMenu)}
            style={{
              width: '100%', padding: '14px 0', fontSize: 16, fontWeight: 600,
              color: '#FFF', backgroundColor: theme.primary,
              border: 'none', borderRadius: 10, cursor: 'pointer',
            }}
          >
            Export Report
          </button>
          {showExportMenu && (
            <div style={{
              position: 'absolute', bottom: '100%', left: 0, right: 0, marginBottom: 8,
              backgroundColor: theme.surface, border: `1px solid ${theme.border}`,
              borderRadius: 10, overflow: 'hidden', boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
            }}>
              {[
                { label: 'Markdown (.md)', onClick: handleExportMarkdown },
                { label: 'Screenshot (PNG)', onClick: handleExportPNG },
                { label: 'Document (PDF)', onClick: handleExportPDF },
              ].map((opt) => (
                <button
                  key={opt.label}
                  onClick={() => { opt.onClick(); setShowExportMenu(false); }}
                  style={{
                    width: '100%', padding: '12px 16px', fontSize: 14,
                    color: theme.text, textAlign: 'left',
                    borderBottom: `1px solid ${theme.border}`,
                    cursor: 'pointer',
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = theme.surfaceSecondary)}
                  onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = 'transparent')}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          )}
        </div>
        <button
          onClick={startScan}
          style={{
            width: '100%',
            padding: '14px 0',
            fontSize: 16,
            fontWeight: 600,
            color: theme.primary,
            backgroundColor: 'transparent',
            border: `1px solid ${theme.primary}`,
            borderRadius: 10,
            cursor: 'pointer',
          }}
        >
          Scan Again
        </button>
      </div>

      {/* Clear Codes Confirmation Modal */}
      {showClearConfirm && (
        <div
          style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 1000,
            backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex',
            alignItems: 'center', justifyContent: 'center',
          }}
          onClick={(e) => { if (e.target === e.currentTarget) setShowClearConfirm(false); }}
        >
          <div style={{
            width: '100%', maxWidth: 420, backgroundColor: theme.surface,
            borderRadius: 16, padding: 24, margin: 16,
          }}>
            <div style={{ fontSize: 18, fontWeight: 700, color: theme.critical, marginBottom: 12 }}>
              Clear All Fault Codes?
            </div>
            <div style={{ fontSize: 14, color: theme.text, lineHeight: '22px', marginBottom: 8 }}>
              This will clear all stored, pending, and permanent DTCs and turn off the Check Engine light.
            </div>
            <div style={{
              fontSize: 13, color: theme.warning, lineHeight: '20px',
              padding: '10px 12px', backgroundColor: theme.warning + '15',
              borderRadius: 8, marginBottom: 16,
            }}>
              Warning: Clearing codes does not fix the underlying problem. If the issue persists, the codes will return. This action cannot be undone.
            </div>
            <div style={{ fontSize: 13, color: theme.textSecondary, marginBottom: 8 }}>
              Type <strong>CLEAR</strong> to confirm:
            </div>
            <input
              value={clearConfirmText}
              onChange={(e) => setClearConfirmText(e.target.value)}
              placeholder="Type CLEAR"
              autoFocus
              style={{
                width: '100%', padding: '10px 12px', fontSize: 15, fontFamily: 'monospace',
                border: `1px solid ${theme.border}`, borderRadius: 8,
                backgroundColor: theme.background, color: theme.text,
                outline: 'none', marginBottom: 16, boxSizing: 'border-box',
              }}
            />
            <div style={{ display: 'flex', gap: 10 }}>
              <button
                onClick={() => setShowClearConfirm(false)}
                style={{
                  flex: 1, padding: '12px 0', fontSize: 15, fontWeight: 600,
                  color: theme.text, backgroundColor: theme.surfaceSecondary,
                  border: `1px solid ${theme.border}`, borderRadius: 10, cursor: 'pointer',
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleClearCodes}
                disabled={clearConfirmText !== 'CLEAR'}
                style={{
                  flex: 1, padding: '12px 0', fontSize: 15, fontWeight: 600,
                  color: '#FFF', backgroundColor: theme.critical,
                  border: 'none', borderRadius: 10,
                  cursor: clearConfirmText === 'CLEAR' ? 'pointer' : 'not-allowed',
                  opacity: clearConfirmText === 'CLEAR' ? 1 : 0.4,
                }}
              >
                Clear Codes
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// --- Freeze Frame Table Sub-component ---

function RawDataLog({ entries, theme }: { entries: RawLogEntry[]; theme: any }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div
      style={{
        backgroundColor: theme.surface,
        border: `1px solid ${theme.border}`,
        borderRadius: 14,
        padding: 16,
        marginBottom: 16,
      }}
    >
      <button
        onClick={() => setExpanded(!expanded)}
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          width: '100%',
          padding: 0,
          background: 'none',
          cursor: 'pointer',
        }}
      >
        <div>
          <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: 0.5, color: theme.textSecondary, textTransform: 'uppercase' as const }}>
            Raw Scan Data
          </div>
          <div style={{ fontSize: 11, color: theme.textTertiary, marginTop: 2, textAlign: 'left' as const }}>
            {entries.length} commands sent — {expanded ? 'click to collapse' : 'click to expand'}
          </div>
        </div>
        <span style={{ fontSize: 16, color: theme.textTertiary }}>{expanded ? '▲' : '▼'}</span>
      </button>
      {expanded && (
        <div style={{ marginTop: 12 }}>
          {entries.map((entry, i) => (
            <div
              key={i}
              style={{
                padding: '10px 0',
                borderTop: i > 0 ? `1px solid ${theme.border}` : 'none',
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 }}>
                <span style={{ fontSize: 13, fontWeight: 600, color: theme.text }}>{entry.description}</span>
                <code style={{ fontSize: 11, color: theme.primary, fontFamily: 'monospace' }}>{entry.command}</code>
              </div>
              <div style={{
                fontSize: 11, fontFamily: 'monospace', color: theme.textSecondary,
                backgroundColor: theme.surfaceSecondary, padding: '6px 8px', borderRadius: 6,
                overflowX: 'auto', whiteSpace: 'pre-wrap', wordBreak: 'break-all',
              }}>
                {entry.rawResponse}
              </div>
              <div style={{ fontSize: 11, color: theme.textTertiary, marginTop: 4 }}>
                Parsed: {entry.parsedSummary}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function FreezeFrameTable({ frame, theme }: { frame: FreezeFrame; theme: any }) {
  const rows = [
    { label: 'Engine RPM', value: frame.rpm, unit: 'RPM' },
    { label: 'Vehicle Speed', value: frame.speed, unit: 'km/h' },
    { label: 'Coolant Temp', value: frame.coolantTemp, unit: '°C' },
    { label: 'Engine Load', value: frame.engineLoad, unit: '%' },
    { label: 'Short Term Fuel Trim', value: frame.shortTermFuelTrim, unit: '%' },
    { label: 'Long Term Fuel Trim', value: frame.longTermFuelTrim, unit: '%' },
    { label: 'Manifold Pressure', value: frame.intakeManifoldPressure, unit: 'kPa' },
    { label: 'Timing Advance', value: frame.timingAdvance, unit: '°' },
  ];

  return (
    <div
      style={{
        backgroundColor: theme.surface,
        border: `1px solid ${theme.border}`,
        borderRadius: 14,
        padding: 16,
        marginBottom: 16,
      }}
    >
      <div
        style={{
          fontSize: 11,
          fontWeight: 600,
          letterSpacing: 0.5,
          color: theme.textSecondary,
          marginBottom: 4,
          textTransform: 'uppercase',
        }}
      >
        Freeze Frame Data
      </div>
      <div style={{ fontSize: 11, color: theme.textTertiary, marginBottom: 10 }}>
        Snapshot of engine data when the first fault code was set
      </div>
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <tbody>
          {rows.map((row) => (
            <tr key={row.label} style={{ borderBottom: `1px solid ${theme.border}` }}>
              <td style={{ padding: '8px 0', fontSize: 14, color: theme.textSecondary }}>
                {row.label}
              </td>
              <td
                style={{
                  padding: '8px 0',
                  fontSize: 14,
                  fontWeight: 600,
                  color: theme.text,
                  textAlign: 'right',
                  fontVariantNumeric: 'tabular-nums',
                }}
              >
                {row.value !== null ? `${row.value} ${row.unit}` : 'N/A'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
